proteins:
  "Cdc3": "P39825"
  "Act1": "P10989"
  "Dp1": "P15924-1"

af_input_jobs:
  Lb2Cas12a_RNA_DNA_complex_8I54_targets:
  - name: Lb2Cas12a_RNA_DNA_complex
    modelSeeds:
    - 1
    - 2
    entities:
    - name: Lb2Cas12a
      type: proteinChain
      count: 1
      useStructureTemplate: true
      maxTemplateDate: '2023-01-01'
      glycans:
      - - BMA
        - 5
      modifications:
      - - CCD_HY3
        - 11
    - name: RNA_33
      type: rnaSequence
    - name: DNA_25
      type: dnaSequence
    - name: DNA_mod
      type: dnaSequence
      modifications:
      - - CCD_6OG
        - 2
      - - CCD_6MA
        - 1
    - name: MG
      type: ion
      count: 1
    af_offset:
      A:
      - 1
      - 1206
      B:
      - 1
      - 33
      C:
      - 1
      - 25
      D:
      - 1
      - 9
      E:
      - 1
      - 1
  Actin_profilin_targets:
  - name: Act1_1_1-375_Cdc3_1_11-120
    modelSeeds: 2
    entities:
    - name: Act1
      type: proteinChain
      range:
      - 1
      - 375
    - name: Cdc3
      range:
      - 11
      - 120
      type: proteinChain
    af_offset:
      A:
      - 1
      - 375
      B:
      - 11
      - 120
  - name: Act1_1_1-375_Cdc3_1_1-127
    entities:
    - name: Act1
      type: proteinChain
    - name: Cdc3
      type: proteinChain
    af_offset:
      A:
      - 1
      - 375
      B:
      - 1
      - 127
  - name: actin_profilin_complex
    entities:
    - name: Act1
      type: proteinChain
    - name: Cdc3
      type: proteinChain
    - name: CCD_ATP
      type: ligand
      count: 1
    - name: MG
      type: ion
      count: 1
    af_offset:
      A:
      - 1
      - 375
      B:
      - 1
      - 127
      C:
      - 1
      - 1
      D:
      - 1
      - 1
  DP_dimer_targets:
  - name: Dp1_2_1021-1950
    modelSeeds: 1
    entities:
    - name: Dp1
      type: proteinChain
      count: 2
      range:
      - 1021
      - 1950
      useStructureTemplate: false
    af_offset:
      A:
      - 1021
      - 1950
      B:
      - 1021
      - 1950
  Collagen_triple_helix_targets:
  - name: collagen_triple_helix
    entities:
    - name: collagen_polypeptide
      type: proteinChain
      count: 3
      maxTemplateDate: '2023-01-01'
      useStructureTemplate: true
    af_offset:
      A:
      - 1
      - 15
      B:
      - 1
      - 15
      C:
      - 1
      - 15
af_master_dirs:
- /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3

af_cycle_dirs:
- /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Collagen_triple_helix_targets

af_job_set_dirs:
- /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Actin_profilin_targets/Act1_1_1-375_Cdc3_1_1-127
- /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Actin_profilin_targets/actin_profilin_complex
- /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Actin_profilin_targets/Act1_1_1-375_Cdc3_1_11-120_subset1
- /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Actin_profilin_targets/Act1_1_1-375_Cdc3_1_11-120_subset2
- /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Lb2Cas12a_RNA_DNA_complex_8I54_targets/Lb2Cas12a_RNA_DNA_complex_subset1
- /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Lb2Cas12a_RNA_DNA_complex_8I54_targets/Lb2Cas12a_RNA_DNA_complex_subset2
best_af3_predictions:
- structure_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/DP_dimer_targets/Dp1_2_1021-1950/dp1_2_1021to1950_4/fold_dp1_2_1021to1950_4_model_0.cif
  data_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/DP_dimer_targets/Dp1_2_1021-1950/dp1_2_1021to1950_4/fold_dp1_2_1021to1950_4_full_data_0.json
  af_offset:
    A:
    - 1021
    - 1950
    B:
    - 1021
    - 1950
- structure_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Lb2Cas12a_RNA_DNA_complex_8I54_targets/Lb2Cas12a_RNA_DNA_complex_subset1/lb2cas12a_rna_dna_complex_1/fold_lb2cas12a_rna_dna_complex_1_model_0.cif
  data_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Lb2Cas12a_RNA_DNA_complex_8I54_targets/Lb2Cas12a_RNA_DNA_complex_subset1/lb2cas12a_rna_dna_complex_1/fold_lb2cas12a_rna_dna_complex_1_full_data_0.json
  af_offset:
    A:
    - 1
    - 1206
    B:
    - 1
    - 33
    C:
    - 1
    - 25
    D:
    - 1
    - 9
    E:
    - 1
    - 1
- structure_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Actin_profilin_targets/Act1_1_1-375_Cdc3_1_11-120_subset2/act1_1_1to375_cdc3_1_11to120_8/fold_act1_1_1to375_cdc3_1_11to120_8_model_0.cif
  data_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Actin_profilin_targets/Act1_1_1-375_Cdc3_1_11-120_subset2/act1_1_1to375_cdc3_1_11to120_8/fold_act1_1_1to375_cdc3_1_11to120_8_full_data_0.json
  af_offset:
    A:
    - 1
    - 375
    B:
    - 11
    - 120
- structure_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Actin_profilin_targets/actin_profilin_complex/actin_profilin_complex/fold_actin_profilin_complex_model_0.cif
  data_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Actin_profilin_targets/actin_profilin_complex/actin_profilin_complex/fold_actin_profilin_complex_full_data_0.json
  af_offset:
    A:
    - 1
    - 375
    B:
    - 1
    - 127
    C:
    - 1
    - 1
    D:
    - 1
    - 1
- structure_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Actin_profilin_targets/Act1_1_1-375_Cdc3_1_11-120_subset1/act1_1_1to375_cdc3_1_11to120_5/fold_act1_1_1to375_cdc3_1_11to120_5_model_0.cif
  data_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Actin_profilin_targets/Act1_1_1-375_Cdc3_1_11-120_subset1/act1_1_1to375_cdc3_1_11to120_5/fold_act1_1_1to375_cdc3_1_11to120_5_full_data_0.json
  af_offset:
    A:
    - 1
    - 375
    B:
    - 11
    - 120
- structure_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Actin_profilin_targets/Act1_1_1-375_Cdc3_1_1-127/act1_1_1to375_cdc3_1_1to127/fold_act1_1_1to375_cdc3_1_1to127_model_0.cif
  data_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Actin_profilin_targets/Act1_1_1-375_Cdc3_1_1-127/act1_1_1to375_cdc3_1_1to127/fold_act1_1_1to375_cdc3_1_1to127_full_data_0.json
  af_offset:
    A:
    - 1
    - 375
    B:
    - 1
    - 127
- structure_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Lb2Cas12a_RNA_DNA_complex_8I54_targets/Lb2Cas12a_RNA_DNA_complex_subset2/lb2cas12a_rna_dna_complex_2/fold_lb2cas12a_rna_dna_complex_2_model_0.cif
  data_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Lb2Cas12a_RNA_DNA_complex_8I54_targets/Lb2Cas12a_RNA_DNA_complex_subset2/lb2cas12a_rna_dna_complex_2/fold_lb2cas12a_rna_dna_complex_2_full_data_0.json
  af_offset:
    A:
    - 1
    - 1206
    B:
    - 1
    - 33
    C:
    - 1
    - 25
    D:
    - 1
    - 9
    E:
    - 1
    - 1
- structure_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Collagen_triple_helix_targets/collagen_triple_helix/fold_collagen_triple_helix_10/fold_collagen_triple_helix_10_model_0.cif
  data_path: 
    /home/omkar/Omkar/AF_PIPELINE/af_pipeline/examples/input/AF_predictions/AF3/Collagen_triple_helix_targets/collagen_triple_helix/fold_collagen_triple_helix_10/fold_collagen_triple_helix_10_full_data_0.json
  af_offset:
    A:
    - 1
    - 15
    B:
    - 1
    - 15
    C:
    - 1
    - 15
